### ISSUE TITLE
Improve general performance

### ISSUE THREAD

**Issue by jaks6** [Stopa/Mobile-Defence-Fortress#65]
Probably has to do with Quadtrees.

One place to look is writing some more specific handling for ground tiles, because we can predict their position etc better, plus there's alot of them.

**Comment by jaks6** [comment]
Having looked into this a bit, it seems the collision algorithm might not be the big bottleneck right now.

Created a wiki page to write ideas down to:
https://github.com/Stopa/Mobile-Defence-Fortress/wiki/Optimization-Ideas

_**It would probably be a good idea to break this issue apart into different optimization techniques as we come up with them.**_

**Comment by Stopa** [comment]
Last week me and @jaks6 spent an evening in the office and came up with a way to singinificantly boost performance - (part of the) bottleneck was in drawing the 1200+ ground tiles. We refactored the ground to consist of "columns" instead of "tiles" and also implemented caching. This approach allows us to not worry about this for some time, however in the future we may have to refactor it to a more complex shape with more complex caching.
